//! Project storage.
//!
//! A project spans three tables — identity and limits in `projects`, its build
//! and start configuration in `project_runtimes`, its published ports in
//! `project_ports` — and they are only ever written together, inside one
//! transaction. A project row without a runtime row is not a partially created
//! project; it is a project the reconciler cannot start and cannot explain.
//!
//! Names that reach Docker (`slug`, `container_name`, `network_name`,
//! `volume_name`, `directory`) are generated by `project-manager` and are
//! `UNIQUE` here as well. The uniqueness is not the defence — the generator is —
//! but a collision would mean two projects sharing a container, so the database
//! refuses it rather than trusting that the generator stayed correct.

use project_host_api_types::{
    ContainerEventType, DeploymentId, DeploymentStatus, DeploymentType, DesiredState, EventId,
    HealthState, PortId, ProjectId, ProjectStatus, ProjectType, RunMode,
};
use sqlx::Row;

use crate::error::{DatabaseError, Result};
use crate::time;
use crate::Database;

/// A project's identity, state and limits.
#[derive(Debug, Clone, PartialEq)]
pub struct ProjectRecord {
    pub id: String,
    pub slug: String,
    pub display_name: String,
    pub description: String,
    pub project_type: String,
    pub icon: Option<String>,
    pub color: Option<String>,

    pub status: String,
    pub desired_state: String,
    pub health: String,

    pub container_id: Option<String>,
    pub container_name: Option<String>,
    pub image_tag: Option<String>,
    pub network_name: Option<String>,
    pub volume_name: Option<String>,

    pub source_type: String,
    pub directory: String,

    /// Where a remote-sourced project came from, and the commit that was
    /// actually checked out. All three are `None` for a local source; the schema
    /// refuses any other combination.
    pub source_url: Option<String>,
    pub source_ref: Option<String>,
    pub source_commit: Option<String>,

    pub autostart: bool,
    pub restart_policy: String,
    pub network_mode: String,

    /// `DOCKER` or `HOST`. Not an enum here for the same reason `status` is
    /// not: this layer stores what the schema allows, and the schema's `CHECK`
    /// is the authority. A project written before host mode existed reads back
    /// as `DOCKER` from the column default.
    pub run_mode: String,

    /// `LOW`, `NORMAL` or `HIGH`. What the resource manager should sacrifice
    /// last when the machine is under pressure. Never a hard limit — it moves
    /// the operating system's scheduling priority and nothing else.
    pub priority: String,
    /// Whether this project running is a reason to hold automatic sleep off.
    pub keep_awake: bool,

    pub memory_limit_mb: i64,
    pub cpu_limit_cores: f64,
    pub storage_limit_mb: i64,
    pub process_limit: i64,

    pub started_at: Option<String>,
    pub stopped_at: Option<String>,
    pub last_exit_code: Option<i64>,
    pub last_failure_at: Option<String>,
    pub last_failure_reason: Option<String>,
    pub restart_count: i64,

    pub archived_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

/// How the project is built and started.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeRecord {
    pub project_id: String,
    pub runtime: String,
    pub runtime_version: String,
    pub package_manager: String,
    pub install_command: Option<String>,
    pub build_command: Option<String>,
    pub start_command: String,
    pub working_dir: String,
    pub entry_file: Option<String>,
    pub publish_dir: Option<String>,
    pub template_id: String,
    pub health_check_type: String,
    pub health_check_target: Option<String>,
    pub health_interval_s: i64,
    pub health_timeout_s: i64,
    pub health_retries: i64,
    pub health_start_period_s: i64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PortRecord {
    pub id: String,
    pub project_id: String,
    pub container_port: i64,
    pub host_port: Option<i64>,
    pub protocol: String,
    pub bind_address: String,
    pub is_primary: bool,
}

/// What a caller supplies to create a project. Every field is already
/// validated by the time it arrives — this struct is storage, not a request.
#[derive(Debug, Clone, PartialEq)]
pub struct NewProject {
    pub slug: String,
    pub display_name: String,
    pub description: String,
    /// The enum rather than a `String`.
    ///
    /// This was a `String`, and the desktop wrote `"GENERIC"` into it — a value
    /// no `CHECK` allows — so every project creation failed with "value
    /// rejected by a database constraint". The parity test could not catch it:
    /// it compares `ProjectType` against the constraint, and those two agreed.
    /// Nothing was watching the literal in between. Now the compiler is.
    pub project_type: ProjectType,
    pub icon: Option<String>,
    pub color: Option<String>,
    pub source_type: String,
    pub directory: String,
    /// Only for `GIT_CLONE` and `REMOTE_ARCHIVE`, and required for them.
    pub source_url: Option<String>,
    /// Only for `GIT_CLONE`.
    pub source_ref: Option<String>,
    pub source_commit: Option<String>,
    pub container_name: String,
    pub network_name: String,
    pub volume_name: String,
    pub autostart: bool,
    pub restart_policy: String,
    pub network_mode: String,
    pub memory_limit_mb: i64,
    pub cpu_limit_cores: f64,
    pub storage_limit_mb: i64,
    pub process_limit: i64,
    pub runtime: RuntimeSpec,
    pub ports: Vec<NewPort>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RuntimeSpec {
    pub runtime: String,
    pub runtime_version: String,
    pub package_manager: String,
    pub install_command: Option<String>,
    pub build_command: Option<String>,
    pub start_command: String,
    pub working_dir: String,
    pub entry_file: Option<String>,
    pub publish_dir: Option<String>,
    pub template_id: String,
    pub health_check_type: String,
    pub health_check_target: Option<String>,
    pub health_interval_s: i64,
    pub health_timeout_s: i64,
    pub health_retries: i64,
    pub health_start_period_s: i64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewPort {
    pub container_port: i64,
    pub host_port: Option<i64>,
    pub protocol: String,
    pub bind_address: String,
    pub is_primary: bool,
}

fn project_from_row(row: &sqlx::sqlite::SqliteRow) -> ProjectRecord {
    ProjectRecord {
        id: row.get("id"),
        slug: row.get("slug"),
        display_name: row.get("display_name"),
        description: row.get("description"),
        project_type: row.get("project_type"),
        icon: row.get("icon"),
        color: row.get("color"),
        status: row.get("status"),
        desired_state: row.get("desired_state"),
        health: row.get("health"),
        container_id: row.get("container_id"),
        container_name: row.get("container_name"),
        image_tag: row.get("image_tag"),
        network_name: row.get("network_name"),
        volume_name: row.get("volume_name"),
        source_type: row.get("source_type"),
        directory: row.get("directory"),
        source_url: row.get("source_url"),
        source_ref: row.get("source_ref"),
        source_commit: row.get("source_commit"),
        autostart: row.get::<i64, _>("autostart") == 1,
        restart_policy: row.get("restart_policy"),
        network_mode: row.get("network_mode"),
        run_mode: row.get("run_mode"),
        priority: row.get("priority"),
        keep_awake: row.get::<i64, _>("keep_awake") == 1,
        memory_limit_mb: row.get("memory_limit_mb"),
        cpu_limit_cores: row.get("cpu_limit_cores"),
        storage_limit_mb: row.get("storage_limit_mb"),
        process_limit: row.get("process_limit"),
        started_at: row.get("started_at"),
        stopped_at: row.get("stopped_at"),
        last_exit_code: row.get("last_exit_code"),
        last_failure_at: row.get("last_failure_at"),
        last_failure_reason: row.get("last_failure_reason"),
        restart_count: row.get("restart_count"),
        archived_at: row.get("archived_at"),
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
    }
}

const PROJECT_COLUMNS: &str = "id, slug, display_name, description, project_type, icon, color,
     status, desired_state, health, container_id, container_name, image_tag,
     network_name, volume_name, source_type, directory,
     source_url, source_ref, source_commit, autostart, restart_policy,
     network_mode, run_mode, priority, keep_awake,
     memory_limit_mb, cpu_limit_cores, storage_limit_mb, process_limit,
     started_at, stopped_at, last_exit_code, last_failure_at, last_failure_reason,
     restart_count, archived_at, created_at, updated_at";

/// Create a project, its runtime and its ports in one transaction.
///
/// The project starts in `CREATING`, not `STOPPED`: nothing has been built yet,
/// and a project that claims to be merely stopped is one the user will try to
/// start before its image exists.
pub async fn create_project(database: &Database, new: &NewProject) -> Result<ProjectRecord> {
    let id = ProjectId::generate().to_string();
    let now = time::now();

    let mut transaction = database.pool().begin().await?;

    sqlx::query(
        "INSERT INTO projects (
            id, slug, display_name, description, project_type, icon, color,
            status, desired_state, health, container_name, network_name, volume_name,
            source_type, directory, source_url, source_ref, source_commit,
            autostart, restart_policy, network_mode,
            memory_limit_mb, cpu_limit_cores, storage_limit_mb, process_limit,
            created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, 'CREATING', 'STOPPED', 'UNKNOWN', ?, ?, ?,
                 ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
    )
    .bind(&id)
    .bind(&new.slug)
    .bind(&new.display_name)
    .bind(&new.description)
    .bind(new.project_type.as_str())
    .bind(&new.icon)
    .bind(&new.color)
    .bind(&new.container_name)
    .bind(&new.network_name)
    .bind(&new.volume_name)
    .bind(&new.source_type)
    .bind(&new.directory)
    .bind(&new.source_url)
    .bind(&new.source_ref)
    .bind(&new.source_commit)
    .bind(i64::from(new.autostart))
    .bind(&new.restart_policy)
    .bind(&new.network_mode)
    .bind(new.memory_limit_mb)
    .bind(new.cpu_limit_cores)
    .bind(new.storage_limit_mb)
    .bind(new.process_limit)
    .bind(&now)
    .bind(&now)
    .execute(&mut *transaction)
    .await?;

    insert_runtime(&mut transaction, &id, &new.runtime).await?;

    for port in &new.ports {
        insert_port(&mut transaction, &id, port).await?;
    }

    transaction.commit().await?;

    find_project(database, &id)
        .await?
        .ok_or(DatabaseError::NotFound { entity: "project" })
}

async fn insert_runtime(
    transaction: &mut sqlx::Transaction<'_, sqlx::Sqlite>,
    project_id: &str,
    runtime: &RuntimeSpec,
) -> Result<()> {
    sqlx::query(
        "INSERT INTO project_runtimes (
            project_id, runtime, runtime_version, package_manager, install_command,
            build_command, start_command, working_dir, entry_file, publish_dir,
            template_id, health_check_type, health_check_target, health_interval_s,
            health_timeout_s, health_retries, health_start_period_s)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
    )
    .bind(project_id)
    .bind(&runtime.runtime)
    .bind(&runtime.runtime_version)
    .bind(&runtime.package_manager)
    .bind(&runtime.install_command)
    .bind(&runtime.build_command)
    .bind(&runtime.start_command)
    .bind(&runtime.working_dir)
    .bind(&runtime.entry_file)
    .bind(&runtime.publish_dir)
    .bind(&runtime.template_id)
    .bind(&runtime.health_check_type)
    .bind(&runtime.health_check_target)
    .bind(runtime.health_interval_s)
    .bind(runtime.health_timeout_s)
    .bind(runtime.health_retries)
    .bind(runtime.health_start_period_s)
    .execute(&mut **transaction)
    .await?;
    Ok(())
}

async fn insert_port(
    transaction: &mut sqlx::Transaction<'_, sqlx::Sqlite>,
    project_id: &str,
    port: &NewPort,
) -> Result<()> {
    sqlx::query(
        "INSERT INTO project_ports (id, project_id, container_port, host_port,
                                    protocol, bind_address, is_primary)
         VALUES (?, ?, ?, ?, ?, ?, ?)",
    )
    .bind(PortId::generate().to_string())
    .bind(project_id)
    .bind(port.container_port)
    .bind(port.host_port)
    .bind(&port.protocol)
    .bind(&port.bind_address)
    .bind(i64::from(port.is_primary))
    .execute(&mut **transaction)
    .await?;
    Ok(())
}

pub async fn find_project(database: &Database, id: &str) -> Result<Option<ProjectRecord>> {
    let row = sqlx::query(&format!(
        "SELECT {PROJECT_COLUMNS} FROM projects WHERE id = ?"
    ))
    .bind(id)
    .fetch_optional(database.pool())
    .await?;
    Ok(row.as_ref().map(project_from_row))
}

pub async fn find_project_by_slug(
    database: &Database,
    slug: &str,
) -> Result<Option<ProjectRecord>> {
    let row = sqlx::query(&format!(
        "SELECT {PROJECT_COLUMNS} FROM projects WHERE slug = ?"
    ))
    .bind(slug)
    .fetch_optional(database.pool())
    .await?;
    Ok(row.as_ref().map(project_from_row))
}

/// One page of projects.
///
/// Keyset pagination on the identifier: UUIDv7 sorts by creation time, so
/// `WHERE id > ?` is both a stable cursor and creation order. An `OFFSET` would
/// skip or repeat rows whenever a project is created mid-scroll.
pub async fn list_projects(
    database: &Database,
    include_archived: bool,
    after: Option<&str>,
    limit: u32,
) -> Result<Vec<ProjectRecord>> {
    let limit = i64::from(limit.clamp(1, 200));
    let sql = format!(
        "SELECT {PROJECT_COLUMNS} FROM projects
         WHERE (? OR archived_at IS NULL)
           AND (? IS NULL OR id > ?)
         ORDER BY id LIMIT ?"
    );
    let rows = sqlx::query(&sql)
        .bind(i64::from(include_archived))
        .bind(after)
        .bind(after)
        .bind(limit)
        .fetch_all(database.pool())
        .await?;
    Ok(rows.iter().map(project_from_row).collect())
}

/// Projects the reconciler should bring back up after a restart or a reboot.
pub async fn projects_wanting_to_run(database: &Database) -> Result<Vec<ProjectRecord>> {
    let rows = sqlx::query(&format!(
        "SELECT {PROJECT_COLUMNS} FROM projects
         WHERE desired_state = 'RUNNING' AND archived_at IS NULL
         ORDER BY id"
    ))
    .fetch_all(database.pool())
    .await?;
    Ok(rows.iter().map(project_from_row).collect())
}

pub async fn find_runtime(database: &Database, project_id: &str) -> Result<Option<RuntimeRecord>> {
    let row = sqlx::query("SELECT * FROM project_runtimes WHERE project_id = ?")
        .bind(project_id)
        .fetch_optional(database.pool())
        .await?;

    Ok(row.map(|row| RuntimeRecord {
        project_id: row.get("project_id"),
        runtime: row.get("runtime"),
        runtime_version: row.get("runtime_version"),
        package_manager: row.get("package_manager"),
        install_command: row.get("install_command"),
        build_command: row.get("build_command"),
        start_command: row.get("start_command"),
        working_dir: row.get("working_dir"),
        entry_file: row.get("entry_file"),
        publish_dir: row.get("publish_dir"),
        template_id: row.get("template_id"),
        health_check_type: row.get("health_check_type"),
        health_check_target: row.get("health_check_target"),
        health_interval_s: row.get("health_interval_s"),
        health_timeout_s: row.get("health_timeout_s"),
        health_retries: row.get("health_retries"),
        health_start_period_s: row.get("health_start_period_s"),
    }))
}

pub async fn list_ports(database: &Database, project_id: &str) -> Result<Vec<PortRecord>> {
    let rows = sqlx::query(
        "SELECT id, project_id, container_port, host_port, protocol, bind_address, is_primary
         FROM project_ports WHERE project_id = ? ORDER BY is_primary DESC, container_port",
    )
    .bind(project_id)
    .fetch_all(database.pool())
    .await?;

    Ok(rows
        .into_iter()
        .map(|row| PortRecord {
            id: row.get("id"),
            project_id: row.get("project_id"),
            container_port: row.get("container_port"),
            host_port: row.get("host_port"),
            protocol: row.get("protocol"),
            bind_address: row.get("bind_address"),
            is_primary: row.get::<i64, _>("is_primary") == 1,
        })
        .collect())
}

/// Every host port currently claimed, so the allocator can avoid them without
/// asking the operating system twice.
pub async fn allocated_host_ports(database: &Database) -> Result<Vec<u16>> {
    let rows: Vec<i64> =
        sqlx::query_scalar("SELECT host_port FROM project_ports WHERE host_port IS NOT NULL")
            .fetch_all(database.pool())
            .await?;
    Ok(rows
        .into_iter()
        .filter_map(|port| u16::try_from(port).ok())
        .collect())
}

/// Record observed state.
///
/// Separate from [`set_desired_state`] on purpose: the reconciler exists because
/// these two disagree, and a single "set state" function is how that distinction
/// gets lost.
///
/// Both parameters are enums rather than `&str` for the reason
/// [`NewProject::project_type`] is: the caller here translates what Docker
/// reports, and Docker's vocabulary is not this column's. `health` in particular
/// arrives from `docker inspect` as `healthy`/`unhealthy`/`starting` — lower
/// case, which no `CHECK` allows — so a `&str` parameter meant every started
/// container with a health check ended in "value rejected by a database
/// constraint". The enum makes that a compile error.
pub async fn set_status(
    database: &Database,
    project_id: &str,
    status: ProjectStatus,
    health: Option<HealthState>,
) -> Result<()> {
    let now = time::now();
    sqlx::query(
        "UPDATE projects
         SET status = ?, health = COALESCE(?, health), updated_at = ?
         WHERE id = ?",
    )
    .bind(status.as_str())
    .bind(health.as_ref().map(HealthState::as_str))
    .bind(&now)
    .bind(project_id)
    .execute(database.pool())
    .await?;
    Ok(())
}

/// Record what the user wants. Survives reboots; this is what makes a project
/// come back up.
/// Change how a project runs.
///
/// Separate from [`ProjectUpdate`] because it is not a preference the way a
/// colour or a description is: it decides which substrate the next start uses,
/// and a project should be stopped before it moves between them.
pub async fn set_run_mode(database: &Database, project_id: &str, mode: RunMode) -> Result<()> {
    let result = sqlx::query("UPDATE projects SET run_mode = ?, updated_at = ? WHERE id = ?")
        .bind(mode.as_str())
        .bind(time::now())
        .bind(project_id)
        .execute(database.pool())
        .await?;
    if result.rows_affected() == 0 {
        return Err(DatabaseError::NotFound { entity: "project" });
    }
    Ok(())
}

pub async fn set_desired_state(
    database: &Database,
    project_id: &str,
    desired: DesiredState,
) -> Result<()> {
    let result = sqlx::query("UPDATE projects SET desired_state = ?, updated_at = ? WHERE id = ?")
        .bind(desired.as_str())
        .bind(time::now())
        .bind(project_id)
        .execute(database.pool())
        .await?;
    if result.rows_affected() == 0 {
        return Err(DatabaseError::NotFound { entity: "project" });
    }
    Ok(())
}

/// Attach the container Docker actually created.
pub async fn record_container(
    database: &Database,
    project_id: &str,
    container_id: Option<&str>,
    image_tag: Option<&str>,
) -> Result<()> {
    sqlx::query(
        "UPDATE projects SET container_id = ?, image_tag = COALESCE(?, image_tag), updated_at = ?
         WHERE id = ?",
    )
    .bind(container_id)
    .bind(image_tag)
    .bind(time::now())
    .bind(project_id)
    .execute(database.pool())
    .await?;
    Ok(())
}

pub async fn record_started(database: &Database, project_id: &str) -> Result<()> {
    let now = time::now();
    sqlx::query(
        "UPDATE projects SET status = 'RUNNING', started_at = ?, stopped_at = NULL, updated_at = ?
         WHERE id = ?",
    )
    .bind(&now)
    .bind(&now)
    .bind(project_id)
    .execute(database.pool())
    .await?;
    Ok(())
}

/// Record a stop, including why.
///
/// A non-zero exit is stored as a failure with its code rather than being
/// flattened to "stopped": "exited 137" is the difference between a user
/// pressing stop and the kernel killing the container for using too much memory.
pub async fn record_stopped(
    database: &Database,
    project_id: &str,
    exit_code: Option<i64>,
    failure_reason: Option<&str>,
) -> Result<()> {
    let now = time::now();
    let failed = failure_reason.is_some() || exit_code.is_some_and(|code| code != 0);
    sqlx::query(
        "UPDATE projects
         SET status = CASE WHEN ? THEN 'FAILED' ELSE 'STOPPED' END,
             stopped_at = ?,
             last_exit_code = ?,
             last_failure_at = CASE WHEN ? THEN ? ELSE last_failure_at END,
             last_failure_reason = CASE WHEN ? THEN ? ELSE last_failure_reason END,
             updated_at = ?
         WHERE id = ?",
    )
    .bind(i64::from(failed))
    .bind(&now)
    .bind(exit_code)
    .bind(i64::from(failed))
    .bind(&now)
    .bind(i64::from(failed))
    .bind(failure_reason)
    .bind(&now)
    .bind(project_id)
    .execute(database.pool())
    .await?;
    Ok(())
}

/// Which project claims a host port, if any does.
///
/// Asked when a start finds a port already bound, so the refusal can name the
/// other project rather than saying only that the port is busy. Archived
/// projects are included deliberately: an archived project's port is still
/// reserved, and "it belongs to a project you archived" is a more useful answer
/// than "something has it".
pub async fn project_holding_port(
    database: &Database,
    host_port: u16,
    excluding: &str,
) -> Result<Option<ProjectRecord>> {
    let row = sqlx::query(&format!(
        "SELECT {PROJECT_COLUMNS} FROM projects
         WHERE id != ? AND id IN (
             SELECT project_id FROM project_ports WHERE host_port = ?
         )
         LIMIT 1"
    ))
    .bind(excluding)
    .bind(i64::from(host_port))
    .fetch_optional(database.pool())
    .await?;
    Ok(row.as_ref().map(project_from_row))
}

/// Change the host port a project's primary mapping uses.
///
/// Only the primary. A project publishing several ports has one the interface
/// treats as *the* port — the one shown, health-checked and passed as `PORT` —
/// and the others are not something the user is offered a control for.
///
/// The `UNIQUE (host_port, protocol, bind_address)` constraint is what stops
/// two projects claiming one port, so a clash here surfaces as a database error
/// rather than being checked for and then raced.
pub async fn set_primary_host_port(
    database: &Database,
    project_id: &str,
    host_port: u16,
) -> Result<()> {
    let ports = list_ports(database, project_id).await?;
    let target = ports
        .iter()
        .find(|port| port.is_primary)
        .or_else(|| ports.first())
        .ok_or(DatabaseError::NotFound {
            entity: "project port",
        })?;

    sqlx::query("UPDATE project_ports SET host_port = ? WHERE id = ?")
        .bind(i64::from(host_port))
        .bind(&target.id)
        .execute(database.pool())
        .await?;

    sqlx::query("UPDATE projects SET updated_at = ? WHERE id = ?")
        .bind(time::now())
        .bind(project_id)
        .execute(database.pool())
        .await?;
    Ok(())
}

/// Record that a project which *was* running died on its own.
///
/// Separate from [`record_stopped`] because the two are different events with
/// different answers. A project that never got off the ground is FAILED — the
/// runtime is missing, the port was taken, the entry file is not there — and the
/// fix is configuration. A project that started cleanly, ran, and then exited
/// non-zero is CRASHED, and the fix is in the user's own code. Writing both as
/// FAILED forced the interface to guess which had happened, and it guessed by
/// showing the same sentence for both.
///
/// `started_at` is deliberately left alone: it is when this run began, and a
/// crash does not change that. `stopped_at` is when it ended.
pub async fn record_crashed(
    database: &Database,
    project_id: &str,
    exit_code: Option<i64>,
    failure_reason: Option<&str>,
) -> Result<()> {
    let now = time::now();
    sqlx::query(
        "UPDATE projects
         SET status = 'CRASHED',
             stopped_at = ?,
             last_exit_code = ?,
             last_failure_at = ?,
             last_failure_reason = ?,
             updated_at = ?
         WHERE id = ?",
    )
    .bind(&now)
    .bind(exit_code)
    .bind(&now)
    .bind(failure_reason)
    .bind(&now)
    .bind(project_id)
    .execute(database.pool())
    .await?;
    Ok(())
}

pub async fn increment_restart_count(database: &Database, project_id: &str) -> Result<i64> {
    sqlx::query(
        "UPDATE projects SET restart_count = restart_count + 1, updated_at = ? WHERE id = ?",
    )
    .bind(time::now())
    .bind(project_id)
    .execute(database.pool())
    .await?;

    sqlx::query_scalar("SELECT restart_count FROM projects WHERE id = ?")
        .bind(project_id)
        .fetch_optional(database.pool())
        .await?
        .ok_or(DatabaseError::NotFound { entity: "project" })
}

/// Update the fields the settings screen can change.
///
/// Deliberately cannot touch `slug`, `directory`, `container_name`,
/// `network_name` or `volume_name`. Those are the project's identity to Docker
/// and the filesystem; changing one would orphan a container or a directory
/// rather than rename it.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ProjectUpdate {
    pub display_name: Option<String>,
    pub description: Option<String>,
    pub icon: Option<String>,
    pub color: Option<String>,
    pub autostart: Option<bool>,
    pub restart_policy: Option<String>,
    pub network_mode: Option<String>,
    /// `LOW`, `NORMAL` or `HIGH`.
    pub priority: Option<String>,
    pub keep_awake: Option<bool>,
    pub memory_limit_mb: Option<i64>,
    pub cpu_limit_cores: Option<f64>,
    pub storage_limit_mb: Option<i64>,
    pub process_limit: Option<i64>,
}

pub async fn update_project(
    database: &Database,
    project_id: &str,
    update: &ProjectUpdate,
) -> Result<ProjectRecord> {
    // `COALESCE(?, column)` keeps this one statement rather than a dynamically
    // assembled SET list — no string building means no way to build the wrong
    // string.
    let result = sqlx::query(
        "UPDATE projects SET
            display_name     = COALESCE(?, display_name),
            description      = COALESCE(?, description),
            icon             = COALESCE(?, icon),
            color            = COALESCE(?, color),
            autostart        = COALESCE(?, autostart),
            restart_policy   = COALESCE(?, restart_policy),
            network_mode     = COALESCE(?, network_mode),
            priority         = COALESCE(?, priority),
            keep_awake       = COALESCE(?, keep_awake),
            memory_limit_mb  = COALESCE(?, memory_limit_mb),
            cpu_limit_cores  = COALESCE(?, cpu_limit_cores),
            storage_limit_mb = COALESCE(?, storage_limit_mb),
            process_limit    = COALESCE(?, process_limit),
            updated_at       = ?
         WHERE id = ?",
    )
    .bind(&update.display_name)
    .bind(&update.description)
    .bind(&update.icon)
    .bind(&update.color)
    .bind(update.autostart.map(i64::from))
    .bind(&update.restart_policy)
    .bind(&update.network_mode)
    .bind(&update.priority)
    .bind(update.keep_awake.map(i64::from))
    .bind(update.memory_limit_mb)
    .bind(update.cpu_limit_cores)
    .bind(update.storage_limit_mb)
    .bind(update.process_limit)
    .bind(time::now())
    .bind(project_id)
    .execute(database.pool())
    .await?;

    if result.rows_affected() == 0 {
        return Err(DatabaseError::NotFound { entity: "project" });
    }

    find_project(database, project_id)
        .await?
        .ok_or(DatabaseError::NotFound { entity: "project" })
}

/// Archive rather than delete. Reversible, and keeps the audit trail meaningful.
pub async fn archive_project(database: &Database, project_id: &str) -> Result<()> {
    let now = time::now();
    let result = sqlx::query(
        "UPDATE projects
         SET archived_at = ?, desired_state = 'ARCHIVED', status = 'ARCHIVED', updated_at = ?
         WHERE id = ? AND archived_at IS NULL",
    )
    .bind(&now)
    .bind(&now)
    .bind(project_id)
    .execute(database.pool())
    .await?;
    if result.rows_affected() == 0 {
        return Err(DatabaseError::NotFound { entity: "project" });
    }
    Ok(())
}

pub async fn unarchive_project(database: &Database, project_id: &str) -> Result<()> {
    sqlx::query(
        "UPDATE projects
         SET archived_at = NULL, desired_state = 'STOPPED', status = 'STOPPED', updated_at = ?
         WHERE id = ?",
    )
    .bind(time::now())
    .bind(project_id)
    .execute(database.pool())
    .await?;
    Ok(())
}

/// Mark a project as being deleted before any container or directory is
/// touched.
///
/// The row is not removed here. If the agent dies partway through removing a
/// container, the `DELETING` status is what tells the next startup that this
/// project's resources need cleaning up rather than restoring.
pub async fn begin_delete(database: &Database, project_id: &str) -> Result<ProjectRecord> {
    let project = find_project(database, project_id)
        .await?
        .ok_or(DatabaseError::NotFound { entity: "project" })?;

    sqlx::query(
        "UPDATE projects SET status = 'DELETING', desired_state = 'STOPPED', updated_at = ?
         WHERE id = ?",
    )
    .bind(time::now())
    .bind(project_id)
    .execute(database.pool())
    .await?;

    Ok(project)
}

/// Remove the row once its container, volume and directory are gone.
///
/// `ON DELETE CASCADE` takes the runtime, ports, variables, deployments, events
/// and backups with it. The audit log does not cascade — see the migration.
pub async fn finish_delete(database: &Database, project_id: &str) -> Result<()> {
    sqlx::query("DELETE FROM projects WHERE id = ?")
        .bind(project_id)
        .execute(database.pool())
        .await?;
    Ok(())
}

/// Projects left mid-delete by a crash.
pub async fn projects_stuck_deleting(database: &Database) -> Result<Vec<ProjectRecord>> {
    let rows = sqlx::query(&format!(
        "SELECT {PROJECT_COLUMNS} FROM projects WHERE status = 'DELETING' ORDER BY id"
    ))
    .fetch_all(database.pool())
    .await?;
    Ok(rows.iter().map(project_from_row).collect())
}

/// A count per status, for the dashboard tiles.
pub async fn status_counts(database: &Database) -> Result<Vec<(String, i64)>> {
    let rows = sqlx::query(
        "SELECT status, COUNT(*) AS total FROM projects
         WHERE archived_at IS NULL GROUP BY status ORDER BY status",
    )
    .fetch_all(database.pool())
    .await?;
    Ok(rows
        .into_iter()
        .map(|row| (row.get("status"), row.get("total")))
        .collect())
}

/// Append a container event. The project's history is built from these.
pub async fn record_container_event(
    database: &Database,
    project_id: &str,
    event_type: ContainerEventType,
    exit_code: Option<i64>,
    detail: Option<&str>,
) -> Result<()> {
    sqlx::query(
        "INSERT INTO container_events (id, project_id, type, exit_code, detail, occurred_at)
         VALUES (?, ?, ?, ?, ?, ?)",
    )
    .bind(EventId::generate().to_string())
    .bind(project_id)
    .bind(event_type.as_str())
    .bind(exit_code)
    .bind(detail)
    .bind(time::now())
    .execute(database.pool())
    .await?;
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ContainerEventRecord {
    pub id: String,
    pub project_id: String,
    pub event_type: String,
    pub exit_code: Option<i64>,
    pub detail: Option<String>,
    pub occurred_at: String,
}

pub async fn list_container_events(
    database: &Database,
    project_id: &str,
    limit: u32,
) -> Result<Vec<ContainerEventRecord>> {
    let rows = sqlx::query(
        "SELECT id, project_id, type, exit_code, detail, occurred_at
         FROM container_events WHERE project_id = ?
         ORDER BY occurred_at DESC, id DESC LIMIT ?",
    )
    .bind(project_id)
    .bind(i64::from(limit.clamp(1, 500)))
    .fetch_all(database.pool())
    .await?;

    Ok(rows
        .into_iter()
        .map(|row| ContainerEventRecord {
            id: row.get("id"),
            project_id: row.get("project_id"),
            event_type: row.get("type"),
            exit_code: row.get("exit_code"),
            detail: row.get("detail"),
            occurred_at: row.get("occurred_at"),
        })
        .collect())
}

// ---------------------------------------------------------------- deployments

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeploymentRecord {
    pub id: String,
    pub project_id: String,
    pub deployment_type: String,
    pub status: String,
    pub operation_id: Option<String>,
    pub image_tag: Option<String>,
    pub error_code: Option<String>,
    pub error_message: Option<String>,
    pub started_at: String,
    pub finished_at: Option<String>,
    pub duration_ms: Option<i64>,
}

pub async fn begin_deployment(
    database: &Database,
    project_id: &str,
    deployment_type: DeploymentType,
    operation_id: Option<&str>,
) -> Result<String> {
    let id = DeploymentId::generate().to_string();
    sqlx::query(
        "INSERT INTO deployments (id, project_id, type, status, operation_id, started_at)
         VALUES (?, ?, ?, 'PENDING', ?, ?)",
    )
    .bind(&id)
    .bind(project_id)
    .bind(deployment_type.as_str())
    .bind(operation_id)
    .bind(time::now())
    .execute(database.pool())
    .await?;
    Ok(id)
}

pub async fn advance_deployment(
    database: &Database,
    deployment_id: &str,
    status: DeploymentStatus,
    image_tag: Option<&str>,
) -> Result<()> {
    sqlx::query(
        "UPDATE deployments SET status = ?, image_tag = COALESCE(?, image_tag) WHERE id = ?",
    )
    .bind(status.as_str())
    .bind(image_tag)
    .bind(deployment_id)
    .execute(database.pool())
    .await?;
    Ok(())
}

/// Close a deployment out, successfully or not.
pub async fn finish_deployment(
    database: &Database,
    deployment_id: &str,
    status: DeploymentStatus,
    error_code: Option<&str>,
    error_message: Option<&str>,
) -> Result<()> {
    let now = time::now();
    sqlx::query(
        "UPDATE deployments
         SET status = ?, error_code = ?, error_message = ?, finished_at = ?,
             duration_ms = CAST((julianday(?) - julianday(started_at)) * 86400000 AS INTEGER)
         WHERE id = ?",
    )
    .bind(status.as_str())
    .bind(error_code)
    .bind(error_message)
    .bind(&now)
    .bind(&now)
    .bind(deployment_id)
    .execute(database.pool())
    .await?;
    Ok(())
}

/// Mark deployments that were still running when the agent died.
///
/// Called during startup recovery: a deployment stuck in `BUILDING` forever is
/// indistinguishable from one in progress, which makes the project unusable.
pub async fn mark_interrupted_deployments(database: &Database) -> Result<u64> {
    let now = time::now();
    let result = sqlx::query(
        "UPDATE deployments
         SET status = 'INTERRUPTED', finished_at = ?,
             error_code = 'AGENT_INTERRUPTED',
             error_message = 'the agent stopped while this deployment was running'
         WHERE status IN ('PENDING','BUILDING','STARTING')",
    )
    .bind(&now)
    .execute(database.pool())
    .await?;
    Ok(result.rows_affected())
}

pub async fn list_deployments(
    database: &Database,
    project_id: &str,
    limit: u32,
) -> Result<Vec<DeploymentRecord>> {
    let rows = sqlx::query(
        "SELECT id, project_id, type, status, operation_id, image_tag,
                error_code, error_message, started_at, finished_at, duration_ms
         FROM deployments WHERE project_id = ?
         ORDER BY started_at DESC, id DESC LIMIT ?",
    )
    .bind(project_id)
    .bind(i64::from(limit.clamp(1, 200)))
    .fetch_all(database.pool())
    .await?;

    Ok(rows
        .into_iter()
        .map(|row| DeploymentRecord {
            id: row.get("id"),
            project_id: row.get("project_id"),
            deployment_type: row.get("type"),
            status: row.get("status"),
            operation_id: row.get("operation_id"),
            image_tag: row.get("image_tag"),
            error_code: row.get("error_code"),
            error_message: row.get("error_message"),
            started_at: row.get("started_at"),
            finished_at: row.get("finished_at"),
            duration_ms: row.get("duration_ms"),
        })
        .collect())
}
