[package]
name = "project-host-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
project-host-database = { version = "0.1.0", path = "../database" }
project-host-discord = { version = "0.1.0", path = "../discord" }
project-host-docker-manager = { version = "0.1.0", path = "../docker-manager" }
project-host-file-manager = { version = "0.1.0", path = "../file-manager" }
project-host-platform = { version = "0.1.0", path = "../platform" }
project-host-security = { version = "0.1.0", path = "../security" }
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.8.6", default-features = false, features = ["sqlite", "runtime-tokio"] }
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "signal", "time", "sync"] }
toml = "1.0.7"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
uuid = { version = "1.20.0", features = ["v4"] }

[lints]
workspace = true

[dev-dependencies]
serde_json = "1.0.151"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time", "sync"] }
sqlx = { version = "0.8.6", default-features = false, features = ["sqlite", "runtime-tokio"] }
