/**
 * Creative & Unusual.
 *
 * The themes that commit to an idea rather than to a mood. Most of the shape
 * and type range lives here: Comic Book's three-pixel borders, Frozen Glass's
 * blur, Blueprint's drafting grid. They are the strongest argument for the
 * trait tokens, and the reason those tokens stop where they do — none of these
 * moves a single element on a screen.
 */

import { ROUNDED, SERIF_DISPLAY, TECHNICAL, DISPLAY_WIDE } from '../fonts';
import type { Theme } from '../types';

export const CREATIVE_THEMES: readonly Theme[] = [
  {
    id: 'steampunk',
    name: 'Steampunk',
    category: 'creative',
    detail: 'Copper and brass over dark iron, with a serif face.',
    tokens: {
      canvas: '#14100c',
      surface: '#1e1811',
      raised: '#262016',
      overlay: '#2e271b',
      edge: '#3a3022',
      edgeStrong: '#604e33',
      ink: '#f5e9d0',
      muted: '#cdb387',
      accent: '#c07f3c',
    },
    traits: {
      fontUi: SERIF_DISPLAY,
      radiusScale: 0.6,
    },
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    category: 'creative',
    detail: 'Black marble with a thin gold rule and a display serif.',
    tokens: {
      canvas: '#08080a',
      surface: '#101013',
      raised: '#16161a',
      overlay: '#1c1c21',
      edge: '#24242a',
      edgeStrong: '#3d3d46',
      ink: '#f6f2e8',
      muted: '#bcb29b',
      accent: '#d4af37',
    },
    traits: {
      fontUi: SERIF_DISPLAY,
      radiusScale: 0.3,
      glow: '#d4af37',
    },
  },
  {
    id: 'frozen-glass',
    name: 'Frozen Glass',
    category: 'creative',
    detail: 'Pale blue panels behind heavy frost. Very soft, very light.',
    tokens: {
      canvas: '#e6eef4',
      surface: '#f4f9fc',
      raised: '#dce8f0',
      overlay: '#ffffff',
      edge: '#c6d8e4',
      edgeStrong: '#95afc0',
      ink: '#0f1c26',
      muted: '#3f5c6c',
      accent: '#2a7fa8',
    },
    traits: {
      blur: '22px',
      radiusScale: 1.6,
      shadowCard: '0 1px 2px rgb(15 28 38 / 0.06), 0 12px 32px rgb(42 127 168 / 0.10)',
    },
  },
  {
    id: 'lava-lamp',
    name: 'Lava Lamp',
    category: 'creative',
    detail: 'Slow blobs of colour drifting behind everything.',
    tokens: {
      canvas: '#150a18',
      surface: '#1e0f23',
      raised: '#26142c',
      overlay: '#2e1836',
      edge: '#3a1f44',
      edgeStrong: '#5e3570',
      ink: '#ffeaf6',
      muted: '#d3aecb',
      accent: '#ff6b9d',
    },
    traits: {
      radiusScale: 1.8,
      glow: '#ff6b9d',
    },
    effect: 'blobs',
  },
  {
    id: 'comic-book',
    name: 'Comic Book',
    category: 'creative',
    detail: 'Cream paper, black outlines three pixels thick, and a halftone screen.',
    tokens: {
      canvas: '#fff8e7',
      surface: '#ffffff',
      raised: '#fff1cc',
      overlay: '#ffffff',
      edge: '#1a1a1a',
      edgeStrong: '#000000',
      ink: '#111111',
      muted: '#4a453c',
      accent: '#e63946',
      ok: '#2a9d8f',
      warn: '#e9a800',
    },
    traits: {
      fontUi: ROUNDED,
      borderWidth: '3px',
      radiusScale: 0.5,
      shadowCard: '4px 4px 0 rgb(0 0 0 / 0.9)',
      shadowRaised: '2px 2px 0 rgb(0 0 0 / 0.85)',
    },
    effect: 'halftone',
  },
  {
    id: 'anime-interface',
    name: 'Anime Interface',
    category: 'creative',
    detail: 'Bright violet and pink with very round corners and a moving sky.',
    tokens: {
      canvas: '#150f26',
      surface: '#1e1533',
      raised: '#251a3e',
      overlay: '#2d2049',
      edge: '#38285a',
      edgeStrong: '#57408c',
      ink: '#fdeaff',
      muted: '#cdb2e3',
      accent: '#ff5fa2',
    },
    traits: {
      fontUi: ROUNDED,
      radiusScale: 1.8,
      glow: '#ff5fa2',
    },
    effect: 'aurora',
  },
  {
    id: 'graffiti',
    name: 'Graffiti',
    category: 'creative',
    detail: 'Concrete grey with one spray-can green and a layer of grain.',
    tokens: {
      canvas: '#17171a',
      surface: '#1f1f23',
      raised: '#26262b',
      overlay: '#2e2e34',
      edge: '#38383f',
      edgeStrong: '#56565f',
      ink: '#f0f0f2',
      muted: '#b2b2ba',
      accent: '#39ff14',
      ok: '#39ff14',
    },
    traits: {
      fontUi: DISPLAY_WIDE,
      radiusScale: 0.4,
      glow: '#39ff14',
    },
    effect: 'noise',
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    category: 'creative',
    detail: 'Drafting blue with white technical lines and a measured grid.',
    tokens: {
      canvas: '#0a2540',
      surface: '#0d2e4f',
      raised: '#10375d',
      overlay: '#14406b',
      edge: '#1d5183',
      edgeStrong: '#3273ad',
      ink: '#eaf4ff',
      muted: '#adcbe7',
      accent: '#7dd3fc',
    },
    traits: {
      fontUi: TECHNICAL,
      radiusScale: 0,
    },
    effect: 'grid',
  },
  {
    id: 'laboratory',
    name: 'Laboratory',
    category: 'creative',
    detail: 'Clinical white and cyan, with instrument-panel type.',
    tokens: {
      canvas: '#eef3f5',
      surface: '#ffffff',
      raised: '#e6eef1',
      overlay: '#ffffff',
      edge: '#d2dfe4',
      edgeStrong: '#9fb6bf',
      ink: '#0d1a1f',
      muted: '#3f5b64',
      accent: '#0891b2',
    },
    traits: {
      fontUi: TECHNICAL,
      radiusScale: 0.5,
    },
  },
  {
    id: 'control-room',
    name: 'Control Room',
    category: 'creative',
    detail: 'Dark operations panels, a status grid, and colour reserved for alarms.',
    tokens: {
      canvas: '#0b0e11',
      surface: '#12161b',
      raised: '#171c22',
      overlay: '#1d232a',
      edge: '#262d36',
      edgeStrong: '#3f4a57',
      ink: '#e7edf3',
      muted: '#aab6c4',
      accent: '#22c55e',
      ok: '#22c55e',
      warn: '#f59e0b',
      danger: '#ef4444',
    },
    traits: {
      fontUi: TECHNICAL,
      radiusScale: 0.25,
    },
    effect: 'grid',
  },
];
