/**
 * Developer.
 *
 * Editor palettes, applied to a whole application rather than to a text buffer.
 * That is a bigger surface than any of them were drawn for, so the ramp is
 * extended in the direction the original already implies — Dracula's background
 * and current-line become canvas and raised, and the missing steps are mixed
 * between them rather than invented.
 *
 * Two of these names belong to products rather than to palettes, and are named
 * for what they are instead: `Editor Dark` and `Repo Dark`. The six that are
 * community colour schemes keep their real names and are credited, both here
 * and in THIRD-PARTY-THEMES.md.
 */

import { MONO } from '../fonts';
import type { Theme } from '../types';

export const DEVELOPER_THEMES: readonly Theme[] = [
  {
    id: 'editor-dark',
    name: 'Editor Dark',
    category: 'developer',
    detail: 'The familiar blue-grey editor dark. Neutral and unsurprising.',
    tokens: {
      canvas: '#1e1e1e',
      surface: '#252526',
      raised: '#2d2d30',
      overlay: '#333337',
      edge: '#3c3c40',
      edgeStrong: '#4d4d52',
      ink: '#e4e4e4',
      muted: '#a8a8a8',
      accent: '#3794ff',
    },
    traits: { fontMono: MONO },
  },
  {
    id: 'repo-dark',
    name: 'Repo Dark',
    category: 'developer',
    detail: 'Charcoal panels and a clear blue. Very little chrome.',
    tokens: {
      canvas: '#0d1117',
      surface: '#161b22',
      raised: '#1c2129',
      overlay: '#22272f',
      edge: '#30363d',
      edgeStrong: '#444c56',
      ink: '#e6edf3',
      muted: '#9aa5b1',
      accent: '#58a6ff',
    },
    traits: { fontMono: MONO },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    category: 'developer',
    detail: 'Dark violet with pink, cyan and green. The comment blue is lifted to stay readable.',
    tokens: {
      canvas: '#21222c',
      surface: '#282a36',
      raised: '#343746',
      overlay: '#3d4051',
      edge: '#44475a',
      edgeStrong: '#565a71',
      ink: '#f8f8f2',
      // Dracula's own comment colour is #6272a4, which measures under 4:1 here.
      // Lifted along the same hue rather than replaced with a grey.
      muted: '#a3add4',
      accent: '#bd93f9',
      ok: '#50fa7b',
      warn: '#f1fa8c',
      danger: '#ff5555',
    },
    traits: { fontMono: MONO },
    credit: {
      work: 'Dracula',
      author: 'Zeno Rocha and contributors',
      licence: 'MIT',
      url: 'https://github.com/dracula/dracula-theme',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    category: 'developer',
    detail: 'Warm dark grey with lime, magenta and orange.',
    tokens: {
      canvas: '#1e1f1c',
      surface: '#272822',
      raised: '#31322b',
      overlay: '#3a3b33',
      edge: '#49483e',
      edgeStrong: '#5f5e52',
      ink: '#f8f8f2',
      muted: '#bab8a6',
      accent: '#a6e22e',
      ok: '#a6e22e',
      warn: '#e6db74',
      danger: '#f92672',
    },
    traits: { fontMono: MONO },
    credit: {
      work: 'Monokai',
      author: 'Wimer Hazenberg',
      licence: 'Original colour scheme — credited, not affiliated',
      url: 'https://monokai.nl/',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    category: 'developer',
    detail: 'Soft slate with balanced syntax colours. Easy for long sessions.',
    tokens: {
      canvas: '#21252b',
      surface: '#282c34',
      raised: '#2f343d',
      overlay: '#363c46',
      edge: '#3e4451',
      edgeStrong: '#515869',
      ink: '#dfe3ea',
      muted: '#a7b1c2',
      accent: '#61afef',
      ok: '#98c379',
      warn: '#e5c07b',
      danger: '#e06c75',
    },
    traits: { fontMono: MONO },
    credit: {
      work: 'One Dark',
      author: 'Atom contributors',
      licence: 'MIT',
      url: 'https://github.com/atom/atom',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    category: 'developer',
    detail: 'Arctic blue-grey with frost accents. Low contrast by design.',
    tokens: {
      canvas: '#2e3440',
      surface: '#3b4252',
      raised: '#434c5e',
      overlay: '#4c566a',
      edge: '#4c566a',
      edgeStrong: '#66738c',
      ink: '#eceff4',
      muted: '#c3ccda',
      accent: '#88c0d0',
      ok: '#a3be8c',
      warn: '#ebcb8b',
      danger: '#bf616a',
    },
    traits: { fontMono: MONO },
    credit: {
      work: 'Nord',
      author: 'Sven Greb / Arctic Ice Studio',
      licence: 'MIT',
      url: 'https://www.nordtheme.com/',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    category: 'developer',
    detail: 'Deep teal with a palette tuned for equal contrast either way up.',
    tokens: {
      canvas: '#002b36',
      surface: '#073642',
      raised: '#0c4351',
      overlay: '#124f5e',
      edge: '#14505c',
      edgeStrong: '#2f6b78',
      ink: '#eee8d5',
      muted: '#a3b1b1',
      accent: '#2aa198',
      ok: '#859900',
      warn: '#b58900',
      danger: '#dc322f',
    },
    traits: { fontMono: MONO },
    credit: {
      work: 'Solarized',
      author: 'Ethan Schoonover',
      licence: 'MIT',
      url: 'https://ethanschoonover.com/solarized/',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    category: 'developer',
    detail: 'The same palette the other way up: warm paper, same relationships.',
    tokens: {
      canvas: '#eee8d5',
      surface: '#fdf6e3',
      raised: '#f6efdc',
      overlay: '#fffdf6',
      edge: '#ded7c1',
      edgeStrong: '#b8b199',
      ink: '#073642',
      muted: '#4e6165',
      accent: '#1c6a94',
      ok: '#5f7000',
      warn: '#8a6800',
      danger: '#c02b28',
    },
    traits: { fontMono: MONO },
    credit: {
      work: 'Solarized',
      author: 'Ethan Schoonover',
      licence: 'MIT',
      url: 'https://ethanschoonover.com/solarized/',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    category: 'developer',
    detail: 'Dark navy with violet and soft blue. Quiet at night.',
    tokens: {
      canvas: '#16161e',
      surface: '#1a1b26',
      raised: '#21222f',
      overlay: '#292e42',
      edge: '#2f3549',
      edgeStrong: '#414868',
      ink: '#c0caf5',
      muted: '#9aa5ce',
      accent: '#7aa2f7',
      ok: '#9ece6a',
      warn: '#e0af68',
      danger: '#f7768e',
    },
    traits: { fontMono: MONO },
    credit: {
      work: 'Tokyo Night',
      author: 'enkia',
      licence: 'MIT',
      url: 'https://github.com/enkia/tokyo-night-vscode-theme',
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin Mocha',
    category: 'developer',
    detail: 'Pastels over a muted dark base. The gentlest of the developer set.',
    tokens: {
      canvas: '#181825',
      surface: '#1e1e2e',
      raised: '#26263a',
      overlay: '#313244',
      edge: '#313244',
      edgeStrong: '#45475a',
      ink: '#cdd6f4',
      muted: '#a6adc8',
      accent: '#cba6f7',
      ok: '#a6e3a1',
      warn: '#f9e2af',
      danger: '#f38ba8',
    },
    traits: { fontMono: MONO },
    credit: {
      work: 'Catppuccin',
      author: 'Catppuccin contributors',
      licence: 'MIT',
      url: 'https://github.com/catppuccin/catppuccin',
    },
  },
];
