/**
 * Futuristic.
 *
 * Two light themes in here on purpose. "Futuristic" defaults to black and neon
 * everywhere, and the laboratory-white end of it — AI Core, Lunar Base,
 * Synthetic Future — is both truer to the brief and the only part of this
 * category anyone can use in a bright room.
 */

import { TECHNICAL } from '../fonts';
import type { Theme } from '../types';

export const FUTURISTIC_THEMES: readonly Theme[] = [
  {
    id: 'ai-core',
    name: 'AI Core',
    category: 'futuristic',
    detail: 'White and silver with a blue glow, and a slow drift of connected points.',
    tokens: {
      canvas: '#eef2f7',
      surface: '#ffffff',
      raised: '#f4f7fb',
      overlay: '#ffffff',
      edge: '#d8e0ea',
      edgeStrong: '#b0bccb',
      ink: '#101822',
      muted: '#4d5a6b',
      accent: '#2563eb',
    },
    traits: {
      fontUi: TECHNICAL,
      glow: '#2563eb',
      shadowCard: '0 1px 2px rgb(16 24 34 / 0.06), 0 8px 24px rgb(37 99 235 / 0.07)',
    },
    effect: 'particles',
  },
  {
    id: 'quantum-interface',
    name: 'Quantum Interface',
    category: 'futuristic',
    detail: 'Deep blue with violet particles behind translucent panels.',
    tokens: {
      canvas: '#070b1a',
      surface: '#0d1226',
      raised: '#131a33',
      overlay: '#1a2242',
      edge: '#212a4d',
      edgeStrong: '#38457a',
      ink: '#e6eaff',
      muted: '#a9b4e2',
      accent: '#a78bfa',
    },
    traits: {
      fontUi: TECHNICAL,
      glow: '#a78bfa',
      blur: '14px',
    },
    effect: 'particles',
  },
  {
    id: 'hologram',
    name: 'Hologram',
    category: 'futuristic',
    detail: 'Projected cyan, scan lines, and panels that look lit from behind.',
    tokens: {
      canvas: '#041014',
      surface: '#071a20',
      raised: '#0a222a',
      overlay: '#0e2b35',
      edge: '#123640',
      edgeStrong: '#1f5c6c',
      ink: '#dcfcff',
      muted: '#93d8e5',
      accent: '#22d3ee',
    },
    traits: {
      fontUi: TECHNICAL,
      glow: '#22d3ee',
      blur: '10px',
    },
    effect: 'scanlines',
  },
  {
    id: 'spaceship-control',
    name: 'Spaceship Control',
    category: 'futuristic',
    detail: 'Metallic panels, amber status lights and squared-off readouts.',
    tokens: {
      canvas: '#0c0e10',
      surface: '#141719',
      raised: '#1a1e21',
      overlay: '#212629',
      edge: '#2a2f33',
      edgeStrong: '#3f464b',
      ink: '#e7ecef',
      muted: '#a9b2b9',
      accent: '#ffb020',
      warn: '#ffb020',
    },
    traits: {
      fontUi: TECHNICAL,
      radiusScale: 0.35,
    },
    effect: 'grid',
  },
  {
    id: 'mars-station',
    name: 'Mars Station',
    category: 'futuristic',
    detail: 'Rust, sand and black. Industrial, dusty, warm.',
    tokens: {
      canvas: '#14100e',
      surface: '#1d1714',
      raised: '#251d19',
      overlay: '#2d241f',
      edge: '#382c25',
      edgeStrong: '#57402f',
      ink: '#f4e6da',
      muted: '#c6a794',
      accent: '#e2703a',
    },
    traits: {
      fontUi: TECHNICAL,
      radiusScale: 0.5,
    },
    effect: 'noise',
  },
  {
    id: 'lunar-base',
    name: 'Lunar Base',
    category: 'futuristic',
    detail: 'Station white and grey with blue indicators. Bright and clinical.',
    tokens: {
      canvas: '#e9ecf1',
      surface: '#f8fafc',
      raised: '#eff2f6',
      overlay: '#ffffff',
      edge: '#d2d8e0',
      edgeStrong: '#a9b3c0',
      ink: '#12161c',
      muted: '#4f5866',
      accent: '#2b7fd4',
    },
    traits: {
      fontUi: TECHNICAL,
      radiusScale: 0.75,
    },
  },
  {
    id: 'deep-space',
    name: 'Deep Space',
    category: 'futuristic',
    detail: 'Black with a field of stars and a nebula glow at the edges.',
    tokens: {
      canvas: '#01030a',
      surface: '#070b17',
      raised: '#0b1020',
      overlay: '#101729',
      edge: '#161d33',
      edgeStrong: '#2a3557',
      ink: '#e2e9f7',
      muted: '#9dabc9',
      accent: '#6366f1',
    },
    traits: {
      glow: '#6366f1',
    },
    effect: 'stars',
  },
  {
    id: 'alien-technology',
    name: 'Alien Technology',
    category: 'futuristic',
    detail: 'Black and emerald, with corners rounded further than anything human.',
    tokens: {
      canvas: '#030806',
      surface: '#06120d',
      raised: '#0a1a13',
      overlay: '#0e2219',
      edge: '#122c20',
      edgeStrong: '#1f4d38',
      ink: '#ddf9eb',
      muted: '#92cfb3',
      accent: '#10d9a0',
      ok: '#10d9a0',
    },
    traits: {
      radiusScale: 1.8,
      glow: '#10d9a0',
    },
    effect: 'particles',
  },
  {
    id: 'time-machine',
    name: 'Time Machine',
    category: 'futuristic',
    detail: 'Brass and dark wood with a cyan charge running through it.',
    tokens: {
      canvas: '#100d08',
      surface: '#1a150d',
      raised: '#221b11',
      overlay: '#2a2216',
      edge: '#35291a',
      edgeStrong: '#57422a',
      ink: '#f6ecd6',
      muted: '#c9b087',
      accent: '#2dd4bf',
      warn: '#d4a53a',
    },
    traits: {
      radiusScale: 1.4,
      glow: '#2dd4bf',
    },
    effect: 'pulse',
  },
  {
    id: 'synthetic-future',
    name: 'Synthetic Future',
    category: 'futuristic',
    detail: 'White surfaces, chrome edges and one electric violet.',
    tokens: {
      canvas: '#f2f4f7',
      surface: '#ffffff',
      raised: '#e9edf2',
      overlay: '#ffffff',
      edge: '#dfe4ea',
      edgeStrong: '#b4bcc7',
      ink: '#0d1117',
      muted: '#4a525e',
      accent: '#7c3aed',
    },
    traits: {
      radiusScale: 1.5,
      glow: '#7c3aed',
      shadowCard: '0 1px 2px rgb(13 17 23 / 0.05), 0 10px 30px rgb(124 58 237 / 0.08)',
    },
  },
];
