/**
 * Gaming.
 *
 * The loudest category, and the one most likely to be left on all day, so the
 * loudness is kept in the accent and the effect rather than the canvas. Two
 * names here are other people's: the souls-like and the block-building one are
 * called `Ashen` and `Blockcraft`, which describe them without borrowing a
 * trademark.
 */

import { DISPLAY_WIDE, SERIF_DISPLAY, TECHNICAL, TERMINAL } from '../fonts';
import type { Theme } from '../types';

export const GAMING_THEMES: readonly Theme[] = [
  {
    id: 'rgb-gaming',
    name: 'RGB Gaming',
    category: 'gaming',
    detail: 'Black hardware with a colour cycle running around the edges.',
    tokens: {
      canvas: '#08080a',
      surface: '#101014',
      raised: '#16161c',
      overlay: '#1c1c23',
      edge: '#26262f',
      edgeStrong: '#3d3d4a',
      ink: '#eeeef3',
      muted: '#acacba',
      accent: '#b829ff',
    },
    traits: {
      glow: '#b829ff',
      radiusScale: 0.6,
    },
    effect: 'aurora',
  },
  {
    id: 'retro-arcade',
    name: 'Retro Arcade',
    category: 'gaming',
    detail: 'Cabinet purple, coin-op yellow, and scan lines over the glass.',
    tokens: {
      canvas: '#0a0618',
      surface: '#140a28',
      raised: '#1b0f35',
      overlay: '#221443',
      edge: '#2c1a55',
      edgeStrong: '#4b2f88',
      ink: '#ffe9f7',
      muted: '#c8abdd',
      accent: '#ffcc00',
      warn: '#ffcc00',
      danger: '#ff3860',
    },
    traits: {
      fontUi: DISPLAY_WIDE,
      radiusScale: 0,
      glow: '#ffcc00',
    },
    effect: 'scanlines',
  },
  {
    id: '8-bit-console',
    name: '8-Bit Console',
    category: 'gaming',
    detail: 'Four shades of handheld green and nothing else. Square corners.',
    tokens: {
      canvas: '#0f2b10',
      surface: '#17401a',
      raised: '#1e5222',
      overlay: '#266528',
      edge: '#2f7a30',
      edgeStrong: '#54a343',
      ink: '#e8f5c8',
      muted: '#bcd992',
      accent: '#9bbc0f',
      ok: '#9bbc0f',
    },
    traits: {
      fontUi: TERMINAL,
      fontMono: TERMINAL,
      radiusScale: 0,
      borderWidth: '2px',
    },
  },
  {
    id: 'achievement-hunter',
    name: 'Achievement Hunter',
    category: 'gaming',
    detail: 'Trophy gold on gunmetal. Everything looks like it unlocks something.',
    tokens: {
      canvas: '#101012',
      surface: '#18181b',
      raised: '#1f1f23',
      overlay: '#26262b',
      edge: '#303036',
      edgeStrong: '#4a4a53',
      ink: '#f3f0e7',
      muted: '#b6ae97',
      accent: '#f5c542',
      warn: '#f5c542',
    },
    traits: {
      glow: '#f5c542',
    },
    effect: 'pulse',
  },
  {
    id: 'battle-royale',
    name: 'Battle Royale',
    category: 'gaming',
    detail: 'Olive drab and blaze orange. Built for reading at a glance.',
    tokens: {
      canvas: '#14150f',
      surface: '#1c1e16',
      raised: '#23261c',
      overlay: '#2a2e22',
      edge: '#343829',
      edgeStrong: '#4f5640',
      ink: '#eff1e5',
      muted: '#b7bda5',
      accent: '#ff6b1a',
      danger: '#e03a1f',
    },
    traits: {
      fontUi: DISPLAY_WIDE,
      radiusScale: 0.25,
    },
  },
  {
    id: 'fantasy-rpg',
    name: 'Fantasy RPG',
    category: 'gaming',
    detail: 'Stone and parchment with gold rules. Serif throughout.',
    tokens: {
      canvas: '#17130f',
      surface: '#211b15',
      raised: '#2a221a',
      overlay: '#332a20',
      edge: '#3f3426',
      edgeStrong: '#61503a',
      ink: '#f2e6ce',
      muted: '#c7b18f',
      accent: '#d4a34a',
    },
    traits: {
      fontUi: SERIF_DISPLAY,
      radiusScale: 0.5,
    },
  },
  {
    id: 'ashen',
    name: 'Ashen',
    category: 'gaming',
    detail: 'Ash grey and faded gold, with embers drifting up behind it.',
    tokens: {
      canvas: '#0b0a09',
      surface: '#131211',
      raised: '#1a1817',
      overlay: '#21201e',
      edge: '#2a2825',
      edgeStrong: '#453f39',
      ink: '#e8e3da',
      muted: '#aea596',
      accent: '#c8a24a',
    },
    traits: {
      fontUi: SERIF_DISPLAY,
      radiusScale: 0.4,
    },
    effect: 'embers',
  },
  {
    id: 'blockcraft',
    name: 'Blockcraft',
    category: 'gaming',
    detail: 'Grass green and dirt brown, in hard-edged blocks with thick borders.',
    tokens: {
      canvas: '#171a14',
      surface: '#20241b',
      raised: '#282d21',
      overlay: '#303628',
      edge: '#3b422f',
      edgeStrong: '#5a6749',
      ink: '#eaeee0',
      muted: '#b5c0a2',
      accent: '#5cba3c',
      ok: '#5cba3c',
    },
    traits: {
      radiusScale: 0,
      borderWidth: '3px',
    },
  },
  {
    id: 'sci-fi-shooter',
    name: 'Sci-Fi Shooter',
    category: 'gaming',
    detail: 'Gunmetal blue with orange targeting marks and a faint HUD grid.',
    tokens: {
      canvas: '#080d12',
      surface: '#0e151c',
      raised: '#131c25',
      overlay: '#18232e',
      edge: '#1f2d3a',
      edgeStrong: '#365064',
      ink: '#e4edf5',
      muted: '#a4b8c9',
      accent: '#ff7a1a',
      warn: '#ff7a1a',
    },
    traits: {
      fontUi: TECHNICAL,
      radiusScale: 0.3,
    },
    effect: 'grid',
  },
  {
    id: 'esports-arena',
    name: 'Esports Arena',
    category: 'gaming',
    detail: 'Broadcast black and electric cyan, with hard-edged panels.',
    tokens: {
      canvas: '#0a0b10',
      surface: '#111319',
      raised: '#171a22',
      overlay: '#1d212b',
      edge: '#262b37',
      edgeStrong: '#3e4658',
      ink: '#eff2f8',
      muted: '#adb6c7',
      accent: '#00e5ff',
    },
    traits: {
      fontUi: DISPLAY_WIDE,
      radiusScale: 0.2,
      glow: '#00e5ff',
    },
  },
];
