/**
 * Hacker & Cyber.
 *
 * The loudest group, and the one where restraint matters most: a terminal green
 * that reads well for five minutes can be unusable for an hour. Every palette
 * here keeps the canvas genuinely dark and puts the saturation into the accent
 * and the effect rather than into the text.
 */

import { MONO, TERMINAL } from '../fonts';
import type { Theme } from '../types';

export const HACKER_THEMES: readonly Theme[] = [
  {
    id: 'matrix-rain',
    name: 'Matrix Rain',
    category: 'hacker',
    detail: 'Black, phosphor green, and code falling behind the interface.',
    tokens: {
      canvas: '#000603',
      surface: '#04120a',
      raised: '#071a0e',
      overlay: '#0a2113',
      edge: '#10331c',
      edgeStrong: '#1a5230',
      ink: '#d7ffe4',
      muted: '#7fd8a1',
      accent: '#22ff88',
      ok: '#22ff88',
    },
    traits: {
      fontMono: MONO,
      glow: '#22ff88',
    },
    effect: 'rain',
  },
  {
    id: 'hacker-terminal',
    name: 'Hacker Terminal',
    category: 'hacker',
    detail: 'Monospace everywhere, a hard green cursor, and scan lines.',
    tokens: {
      canvas: '#08090a',
      surface: '#0d0f10',
      raised: '#121517',
      overlay: '#171b1d',
      edge: '#1e2427',
      edgeStrong: '#2b3438',
      ink: '#c9f7d6',
      muted: '#8bbd9d',
      accent: '#33d17a',
      ok: '#33d17a',
    },
    traits: {
      fontUi: TERMINAL,
      fontMono: TERMINAL,
      radiusScale: 0,
    },
    effect: 'scanlines',
  },
  {
    id: 'red-team',
    name: 'Red Team',
    category: 'hacker',
    detail: 'Offensive security: near-black, alert red, everything urgent.',
    tokens: {
      canvas: '#0b0708',
      surface: '#140a0c',
      raised: '#1b0e11',
      overlay: '#221216',
      edge: '#2c161a',
      edgeStrong: '#43222a',
      ink: '#f3dee1',
      muted: '#c69ba3',
      accent: '#ff3b47',
      danger: '#ff3b47',
      warn: '#ff9f1c',
    },
    traits: {
      fontMono: MONO,
      glow: '#ff3b47',
    },
    effect: 'pulse',
  },
  {
    id: 'blue-team',
    name: 'Blue Team',
    category: 'hacker',
    detail: 'Defensive navy with a cyan grid, for watching rather than breaking.',
    tokens: {
      canvas: '#050a12',
      surface: '#0a1220',
      raised: '#0e1a2c',
      overlay: '#132238',
      edge: '#1a2c46',
      edgeStrong: '#294263',
      ink: '#dce9f7',
      muted: '#98b5d4',
      accent: '#38bdf8',
    },
    traits: {
      fontMono: MONO,
    },
    effect: 'grid',
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    category: 'hacker',
    detail: 'Violet dark, magenta accent, and a gradient that will not sit still.',
    tokens: {
      canvas: '#0a0512',
      surface: '#120a1f',
      raised: '#180e29',
      overlay: '#1f1234',
      edge: '#2a1846',
      edgeStrong: '#402467',
      ink: '#f4e9ff',
      muted: '#bda2d8',
      accent: '#ff2fd0',
    },
    traits: {
      glow: '#ff2fd0',
    },
    effect: 'aurora',
  },
  {
    id: 'digital-underground',
    name: 'Digital Underground',
    category: 'hacker',
    detail: 'Concrete grey, acid green, and a layer of grain over everything.',
    tokens: {
      canvas: '#0d0f0d',
      surface: '#141814',
      raised: '#1a1f19',
      overlay: '#202620',
      edge: '#283028',
      edgeStrong: '#3a463a',
      ink: '#e6ede4',
      muted: '#a5b6a2',
      accent: '#a3e635',
      ok: '#a3e635',
    },
    traits: {
      fontMono: MONO,
    },
    effect: 'noise',
  },
  {
    id: 'zero-day',
    name: 'Zero Day',
    category: 'hacker',
    detail: 'Neutral black with a single hazard orange. Nothing else competes.',
    tokens: {
      canvas: '#0a0a0b',
      surface: '#121213',
      raised: '#18181a',
      overlay: '#1f1f21',
      edge: '#292a2c',
      edgeStrong: '#3c3d40',
      ink: '#f0ede8',
      muted: '#aca69d',
      accent: '#ff7a00',
      warn: '#ff7a00',
    },
    traits: {
      fontMono: MONO,
      radiusScale: 0.5,
    },
    effect: 'pulse',
  },
  {
    id: 'dark-web',
    name: 'Dark Web',
    category: 'hacker',
    detail: 'Almost no light, muted violet, deliberately low key.',
    tokens: {
      canvas: '#060507',
      surface: '#0c0a0f',
      raised: '#110e16',
      overlay: '#16121d',
      edge: '#1d1826',
      edgeStrong: '#2c2439',
      ink: '#ded7e7',
      muted: '#a094b1',
      accent: '#8b5cf6',
    },
    traits: {
      fontMono: MONO,
    },
    effect: 'noise',
  },
  {
    id: 'anonymous',
    name: 'Anonymous',
    category: 'hacker',
    detail: 'Pure greyscale with one green. Terminal overlay, no colour opinions.',
    tokens: {
      canvas: '#070707',
      surface: '#0e0e0e',
      raised: '#141414',
      overlay: '#1a1a1a',
      edge: '#232323',
      edgeStrong: '#343434',
      ink: '#ededed',
      muted: '#a8a8a8',
      accent: '#3ddc84',
      ok: '#3ddc84',
    },
    traits: {
      fontUi: MONO,
      fontMono: MONO,
    },
    effect: 'scanlines',
  },
  {
    id: 'root-access',
    name: 'Root Access',
    category: 'hacker',
    detail: 'Command-line black with red permissions. Square, plain, unfriendly.',
    tokens: {
      canvas: '#050505',
      surface: '#0c0b0b',
      raised: '#121010',
      overlay: '#181515',
      edge: '#221d1d',
      edgeStrong: '#352c2c',
      ink: '#ececec',
      muted: '#a69e9e',
      accent: '#ef4444',
      danger: '#ef4444',
    },
    traits: {
      fontUi: TERMINAL,
      fontMono: TERMINAL,
      radiusScale: 0,
    },
    effect: 'scanlines',
  },
];
