/**
 * Minimal & Professional.
 *
 * The group someone lands on when they want the application to disappear. Two
 * of these carry history: `Pure Dark` and `Pure Light` are the values the
 * application shipped as `dark` and `light`, unchanged, so anyone migrating
 * sees exactly what they saw yesterday. `Amber` and `Midnight` are here for the
 * same reason — they were real settings, and deleting a theme someone chose is
 * not a rename.
 */

import { SERIF, SERIF_DISPLAY } from '../fonts';
import type { Theme } from '../types';

export const MINIMAL_THEMES: readonly Theme[] = [
  {
    id: 'pure-dark',
    name: 'Pure Dark',
    category: 'minimal',
    detail: 'The default charcoal. Neutral, so project colours stay readable.',
    tokens: {
      canvas: '#0e0e10',
      surface: '#16161a',
      raised: '#1c1c21',
      overlay: '#212127',
      edge: '#26262d',
      edgeStrong: '#35353e',
      ink: '#e8e8ec',
      muted: '#9d9da8',
      faint: '#6e6e79',
      accent: '#3b82f6',
    },
  },
  {
    id: 'pure-light',
    name: 'Pure Light',
    category: 'minimal',
    detail: 'For bright rooms and screen sharing.',
    tokens: {
      canvas: '#f4f4f6',
      surface: '#ffffff',
      raised: '#ececed',
      overlay: '#ffffff',
      edge: '#dededf',
      edgeStrong: '#c3c3c6',
      ink: '#16161a',
      muted: '#56565f',
      faint: '#71717a',
      accent: '#2563eb',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    category: 'minimal',
    detail: 'Deep blue-black with more contrast between layers.',
    tokens: {
      canvas: '#0a0d16',
      surface: '#10141f',
      raised: '#161b2b',
      overlay: '#1c2336',
      edge: '#232b40',
      edgeStrong: '#33405c',
      ink: '#e6e9f2',
      muted: '#9aa3bd',
      faint: '#6b7593',
      accent: '#6366f1',
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    category: 'minimal',
    detail: 'Warm greys with a low-blue cast, for long evenings.',
    tokens: {
      canvas: '#14100b',
      surface: '#1c1710',
      raised: '#241d14',
      overlay: '#2b2318',
      edge: '#33291c',
      edgeStrong: '#453725',
      ink: '#f0e7d8',
      muted: '#b8a58f',
      faint: '#8a7a63',
      accent: '#f59e0b',
    },
  },
  {
    id: 'graphite',
    name: 'Graphite',
    category: 'minimal',
    detail: 'Neutral grey with no colour at all, including the accent.',
    tokens: {
      canvas: '#131315',
      surface: '#1a1a1d',
      raised: '#202024',
      overlay: '#26262b',
      edge: '#2f2f35',
      edgeStrong: '#46464d',
      ink: '#e9e9ea',
      muted: '#a6a6ab',
      accent: '#a1a1aa',
    },
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    category: 'minimal',
    detail: 'White panels and a navy accent. Safe in any meeting.',
    tokens: {
      canvas: '#f1f4f8',
      surface: '#ffffff',
      raised: '#e9eef5',
      overlay: '#ffffff',
      edge: '#d7dfe9',
      edgeStrong: '#aebbca',
      ink: '#0f1b2a',
      muted: '#48586b',
      accent: '#1d4ed8',
    },
  },
  {
    id: 'executive-black',
    name: 'Executive Black',
    category: 'minimal',
    detail: 'Black and graphite with a restrained gold and a serif face.',
    tokens: {
      canvas: '#0a0a0a',
      surface: '#121212',
      raised: '#191919',
      overlay: '#1f1f1f',
      edge: '#272727',
      edgeStrong: '#3d3d3d',
      ink: '#ececec',
      muted: '#a8a8a8',
      accent: '#c9a227',
    },
    traits: {
      fontUi: SERIF_DISPLAY,
      radiusScale: 0.35,
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    category: 'minimal',
    detail: 'Off-white stock, ink-dark text, hairline rules.',
    tokens: {
      canvas: '#f6f3ec',
      surface: '#fffdf8',
      raised: '#efeade',
      overlay: '#fffdf8',
      edge: '#ddd7c8',
      edgeStrong: '#b5ad9a',
      ink: '#1c1a16',
      muted: '#575147',
      accent: '#2f5f8f',
    },
    traits: {
      fontUi: SERIF,
      radiusScale: 0.25,
      shadowCard: '0 1px 1px rgb(28 26 22 / 0.05)',
    },
  },
  {
    id: 'glass-minimal',
    name: 'Glass Minimal',
    category: 'minimal',
    detail: 'Translucent cards over a blurred background. Very soft edges.',
    tokens: {
      canvas: '#101318',
      surface: '#171b23',
      raised: '#1d222b',
      overlay: '#242a35',
      edge: '#2a3140',
      edgeStrong: '#404a5d',
      ink: '#eaeef5',
      muted: '#acb5c4',
      accent: '#60a5fa',
    },
    traits: {
      blur: '18px',
      radiusScale: 1.4,
      shadowCard: '0 1px 2px rgb(0 0 0 / 0.4), 0 16px 40px rgb(0 0 0 / 0.35)',
    },
  },
  {
    id: 'soft-gray',
    name: 'Soft Gray',
    category: 'minimal',
    detail: 'Calm mid-grey surfaces with a muted slate accent.',
    tokens: {
      canvas: '#1a1a1c',
      surface: '#212124',
      raised: '#27272b',
      overlay: '#2e2e33',
      edge: '#37373d',
      edgeStrong: '#4e4e56',
      ink: '#e6e6e8',
      muted: '#aeaeb5',
      accent: '#8fa8c6',
    },
    traits: {
      radiusScale: 1.2,
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    category: 'minimal',
    detail: 'Black, white and yellow, held to 7:1 rather than 4.5:1.',
    tokens: {
      canvas: '#000000',
      surface: '#0a0a0a',
      raised: '#141414',
      overlay: '#1c1c1c',
      edge: '#6a6a6a',
      edgeStrong: '#ffffff',
      ink: '#ffffff',
      muted: '#e6e6e6',
      faint: '#c4c4c4',
      accent: '#ffff00',
      ok: '#00ff7f',
      warn: '#ffd400',
      danger: '#ff5c5c',
    },
    traits: {
      borderWidth: '2px',
      radiusScale: 0.25,
    },
    contrastTarget: 7,
  },
];
