/**
 * Nature.
 *
 * Landscapes at the saturation of a room rather than of a photograph. A forest
 * photograph is far greener than a forest theme can be: the canvas is behind
 * text for eight hours, so each of these takes the hue and drops most of the
 * chroma out of it, keeping the saturation for the accent.
 */

import type { Theme } from '../types';

export const NATURE_THEMES: readonly Theme[] = [
  {
    id: 'forest',
    name: 'Forest',
    category: 'nature',
    detail: 'Deep green under canopy, with moss and bark in the surfaces.',
    tokens: {
      canvas: '#0d140f',
      surface: '#141d16',
      raised: '#1a251c',
      overlay: '#202d22',
      edge: '#28372a',
      edgeStrong: '#405644',
      ink: '#e7f1e7',
      muted: '#acc3ad',
      accent: '#4ade80',
      ok: '#4ade80',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    category: 'nature',
    detail: 'Deep water blue with a turquoise surface light.',
    tokens: {
      canvas: '#04121c',
      surface: '#071c2b',
      raised: '#0a2436',
      overlay: '#0e2d42',
      edge: '#123950',
      edgeStrong: '#215d7d',
      ink: '#e0f1fb',
      muted: '#9ec3d8',
      accent: '#22d3ee',
    },
  },
  {
    id: 'arctic',
    name: 'Arctic',
    category: 'nature',
    detail: 'Ice white and pale blue, with frosted panels.',
    tokens: {
      canvas: '#eef4f8',
      surface: '#ffffff',
      raised: '#e4eef4',
      overlay: '#ffffff',
      edge: '#d0e0ea',
      edgeStrong: '#a3bccc',
      ink: '#0e1c24',
      muted: '#42606e',
      accent: '#0e7490',
    },
    traits: {
      blur: '12px',
      radiusScale: 1.3,
    },
  },
  {
    id: 'volcano',
    name: 'Volcano',
    category: 'nature',
    detail: 'Cooled black rock with lava in the accent and embers rising.',
    tokens: {
      canvas: '#0d0908',
      surface: '#150e0c',
      raised: '#1c1310',
      overlay: '#241814',
      edge: '#2e1e19',
      edgeStrong: '#4e3128',
      ink: '#f6e5de',
      muted: '#c8a294',
      accent: '#ff5722',
      danger: '#ff3b30',
    },
    traits: {
      glow: '#ff5722',
    },
    effect: 'embers',
  },
  {
    id: 'desert',
    name: 'Desert',
    category: 'nature',
    detail: 'Sand, dark earth and low evening sun.',
    tokens: {
      canvas: '#171208',
      surface: '#21190c',
      raised: '#292010',
      overlay: '#322714',
      edge: '#3d301a',
      edgeStrong: '#614c29',
      ink: '#f7ecd4',
      muted: '#cdb188',
      accent: '#e9a13b',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    category: 'nature',
    detail: 'Dusk violet with orange and pink moving slowly behind it.',
    tokens: {
      canvas: '#1a0d1a',
      surface: '#241228',
      raised: '#2d1732',
      overlay: '#371c3d',
      edge: '#43234a',
      edgeStrong: '#693974',
      ink: '#ffeaf3',
      muted: '#d5aec6',
      accent: '#fb7185',
    },
    effect: 'aurora',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    category: 'nature',
    detail: 'A dark sky with green and violet light drifting across it.',
    tokens: {
      canvas: '#050b14',
      surface: '#0a1420',
      raised: '#0e1b2b',
      overlay: '#132336',
      edge: '#182b42',
      edgeStrong: '#2b4d6e',
      ink: '#e3f1f6',
      muted: '#a2c2cf',
      accent: '#34d399',
    },
    traits: {
      glow: '#34d399',
    },
    effect: 'aurora',
  },
  {
    id: 'rainy-night',
    name: 'Rainy Night',
    category: 'nature',
    detail: 'Wet blue-grey glass with rain running down it.',
    tokens: {
      canvas: '#10141a',
      surface: '#181d25',
      raised: '#1e242e',
      overlay: '#252c38',
      edge: '#2d3542',
      edgeStrong: '#455264',
      ink: '#e5ebf3',
      muted: '#abb8c8',
      accent: '#7dd3fc',
    },
    traits: {
      blur: '14px',
    },
    effect: 'drizzle',
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    category: 'nature',
    detail: 'Pale pink and white, with petals falling past.',
    tokens: {
      canvas: '#fdf2f5',
      surface: '#ffffff',
      raised: '#fbe8ee',
      overlay: '#ffffff',
      edge: '#f2d6de',
      edgeStrong: '#d4a8b6',
      ink: '#2a1a20',
      muted: '#6b4b56',
      accent: '#c2185b',
    },
    traits: {
      radiusScale: 1.4,
    },
    effect: 'petals',
  },
  {
    id: 'tropical',
    name: 'Tropical',
    category: 'nature',
    detail: 'Jungle green with turquoise and a hot yellow warning.',
    tokens: {
      canvas: '#04140f',
      surface: '#071e17',
      raised: '#0a271e',
      overlay: '#0e3125',
      edge: '#123d2e',
      edgeStrong: '#1f6650',
      ink: '#e4f8ef',
      muted: '#9cd5be',
      accent: '#2dd4bf',
      warn: '#facc15',
      ok: '#4ade80',
    },
    traits: {
      radiusScale: 1.3,
    },
  },
];
