//! Prefixed identifiers.
//!
//! Every identifier in the system is a UUIDv7 with a short type prefix, e.g.
//! `prj_01930f4c…`. Two properties matter:
//!
//! * UUIDv7 sorts by creation time, so cursor pagination is `WHERE id > ?`
//!   rather than an offset that skips and duplicates rows under concurrent
//!   writes.
//! * The prefix makes a misrouted identifier obvious in a log or an error
//!   message, instead of one opaque UUID looking exactly like another.
//!
//! Identifiers are generated by the server. Nothing derived from user input
//! ever becomes an identifier — see `docs/security.md` §5.

use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

/// Rejected identifier, with the reason kept specific enough to debug.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum IdError {
    #[error("identifier is empty")]
    Empty,
    #[error("expected prefix `{expected}`, found `{found}`")]
    WrongPrefix {
        expected: &'static str,
        found: String,
    },
    #[error("identifier body is not a valid UUID")]
    InvalidUuid,
}

macro_rules! prefixed_id {
    ($(#[$meta:meta])* $name:ident, $prefix:literal) => {
        $(#[$meta])*
        #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
        #[serde(transparent)]
        pub struct $name(String);

        impl $name {
            /// The prefix every value of this type carries, without the underscore.
            pub const PREFIX: &'static str = $prefix;

            /// Mint a new identifier. Time-ordered, so inserts stay append-like.
            pub fn generate() -> Self {
                Self(format!("{}_{}", $prefix, uuid::Uuid::now_v7().simple()))
            }

            /// Validate an identifier that arrived from outside.
            pub fn parse(value: &str) -> Result<Self, IdError> {
                if value.is_empty() {
                    return Err(IdError::Empty);
                }
                let Some(body) = value.strip_prefix(concat!($prefix, "_")) else {
                    let found = value.split('_').next().unwrap_or(value).to_string();
                    return Err(IdError::WrongPrefix { expected: $prefix, found });
                };
                if uuid::Uuid::parse_str(body).is_err() {
                    return Err(IdError::InvalidUuid);
                }
                Ok(Self(value.to_string()))
            }

            /// The full identifier, prefix included.
            pub fn as_str(&self) -> &str {
                &self.0
            }

            /// The UUID portion, used where a bare UUID is required (container
            /// labels, directory names).
            pub fn body(&self) -> &str {
                self.0.strip_prefix(concat!($prefix, "_")).unwrap_or(&self.0)
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl FromStr for $name {
            type Err = IdError;
            fn from_str(s: &str) -> Result<Self, Self::Err> {
                Self::parse(s)
            }
        }

        impl schemars::JsonSchema for $name {
            fn schema_name() -> std::borrow::Cow<'static, str> {
                std::borrow::Cow::Borrowed(stringify!($name))
            }

            fn json_schema(_: &mut schemars::SchemaGenerator) -> schemars::Schema {
                schemars::json_schema!({
                    "type": "string",
                    "description": concat!("Identifier prefixed with `", $prefix, "_`."),
                })
            }
        }
    };
}

prefixed_id!(
    /// A user account.
    UserId, "usr");
prefixed_id!(
    /// An authenticated session.
    SessionId, "ses");
prefixed_id!(
    /// A paired remote client.
    ClientId, "cli");
prefixed_id!(
    /// A hosted project.
    ProjectId, "prj");
prefixed_id!(
    /// One build-and-start attempt for a project.
    DeploymentId, "dep");
prefixed_id!(
    /// A stored backup archive.
    BackupId, "bkp");
prefixed_id!(
    /// A long-running agent operation.
    OperationId, "op");
prefixed_id!(
    /// An audit log entry.
    AuditId, "aud");
prefixed_id!(
    /// A user-facing notification.
    NotificationId, "ntf");
prefixed_id!(
    /// An environment variable row.
    EnvVarId, "env");
prefixed_id!(
    /// A published port allocation.
    PortId, "prt");
prefixed_id!(
    /// One observed container lifecycle event.
    EventId, "evt");
prefixed_id!(
    /// A saved server connection, stored by the desktop client.
    ConnectionId, "con");
prefixed_id!(
    /// A linked Discord server.
    ///
    /// Distinct from the Discord guild id it refers to: that one is Discord's,
    /// is a 64-bit number, and would be a poor primary key for rows we own.
    GuildLinkId, "gld");
prefixed_id!(
    /// One "this role or person may do this much" rule.
    GrantId, "grt");
prefixed_id!(
    /// One Discord bot this installation can connect as.
    ///
    /// Distinct from the Discord application id it carries: that one is
    /// Discord's, and an installation may hold a token for an application it
    /// later replaces.
    BotId, "bot");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_ids_carry_their_prefix() {
        let id = ProjectId::generate();
        assert!(id.as_str().starts_with("prj_"), "got {id}");
        assert_eq!(ProjectId::parse(id.as_str()), Ok(id));
    }

    #[test]
    fn generated_ids_are_time_ordered() {
        let first = ProjectId::generate();
        let second = ProjectId::generate();
        // UUIDv7 embeds a millisecond timestamp; within the same millisecond the
        // random tail still yields a total order, so this is a strict inequality
        // rather than a timing-dependent assertion.
        assert_ne!(first, second);
    }

    #[test]
    fn wrong_prefix_is_rejected_with_the_prefix_that_was_found() {
        let backup = BackupId::generate();
        let err = ProjectId::parse(backup.as_str()).unwrap_err();
        assert_eq!(
            err,
            IdError::WrongPrefix {
                expected: "prj",
                found: "bkp".to_string()
            }
        );
    }

    #[test]
    fn malformed_body_is_rejected() {
        assert_eq!(
            ProjectId::parse("prj_nothexatall"),
            Err(IdError::InvalidUuid)
        );
        assert_eq!(ProjectId::parse(""), Err(IdError::Empty));
    }

    #[test]
    fn body_strips_the_prefix() {
        let id = ProjectId::generate();
        assert!(!id.body().contains('_'));
        assert_eq!(id.body().len(), 32);
    }

    #[test]
    fn serialises_as_a_bare_string() {
        let id = ProjectId::generate();
        let json = serde_json::to_string(&id).unwrap();
        assert_eq!(json, format!("\"{id}\""));
    }
}
